import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import Navbar from '@/components/Navbar'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Toaster position='top-center' richColors />
        <header>
          <Link href={'/'}>AnimeHub</Link>
          <Link href={'/favorites'}>Favorites</Link>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}
